language: python
dist: xenial
os:
  - linux

python:
  - '3.5'
  - '3.6'
  - '3.7'

env:
  - ''  # Run with default environment
  - PYTHONOPTIMIZE=1

cache:
  directories:
    - $HOME/.cache/pypoetry

before_install:
  - pip install poetry

install:
  - poetry install

script:
  - ./scripts/test.sh
  - ./scripts/benchmark.sh
  - poetry build 
